import { env } from '@libs/shared/config';

export const NEXT_PUBLIC_IS_DEV = env.NEXT_PUBLIC_IS_DEV;

export const NEXT_PUBLIC_API_ENDPOINT = env.NEXT_PUBLIC_API_ENDPOINT;
export const NEXT_PUBLIC_API_GQL_URL = env.NEXT_PUBLIC_API_GQL_URL;

export const NEXT_PUBLIC_GISCUS_REPO = env.NEXT_PUBLIC_GISCUS_REPO;
export const NEXT_PUBLIC_GISCUS_REPOSITORY_ID = env.NEXT_PUBLIC_GISCUS_REPOSITORY_ID;
export const NEXT_PUBLIC_GISCUS_CATEGORY = env.NEXT_PUBLIC_GISCUS_CATEGORY;
export const NEXT_PUBLIC_GISCUS_CATEGORY_ID = env.NEXT_PUBLIC_GISCUS_CATEGORY_ID;
