version: "3.1"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mongodb/data

volumes:
  db-data:
