version: "3"

services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    command: --replSet rs0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ./mongodb/initdb.d:/docker-entrypoint-initdb.d
      - ./mongodb/data:/data/db